version: '2.4'
services:
  grounded_sam2_ros:
    image: grounded_sam2_ros
    privileged: true
    build:
      context: ../../src/grounded_sam2_ros
      dockerfile: Dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../torch_cache/gsam2/:/root/.cache/torch
      - "../../src/grounded_sam2_ros:/root/grounded_sam2_ros:rw"
      - ../../config:/root/config

    environment: 
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash -c "source /opt/ros/noetic/setup.bash;
                      source /root/catkin_ws/devel/setup.bash;
                      python3.10 -m pip install --no-build-isolation -e  /root/grounded_sam2_ros/grounding_dino;
                      export CUDA_HOME=/usr/local/cuda-12.1/;
                      rosparam load /root/config/gsam2.yaml;
                      python3 /root/grounded_sam2_ros/grounded_sam_2_ros_service.py"
    stdin_open: true
    tty: true 